# Generated by Django 4.2.4 on 2023-08-12 20:57

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'trip_status',
                'verbose_name_plural': 'trip_statuses',
                'ordering': ('-created_at',),
                'default_related_name': 'trip_statuses',
                'indexes': [models.Index(fields=['id'], name='trips_trips_id_52f3e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=32)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_time', models.DateTimeField(null=True)),
                ('distance', models.FloatField()),
                ('fare', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trips.tripstatus')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ('-created_at',),
                'default_related_name': 'trips',
                'indexes': [models.Index(fields=['id'], name='trips_trip_id_206c85_idx')],
            },
        ),
    ]
