# Generated by Django 4.2.4 on 2023-08-14 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'cancellation_reason',
                'verbose_name_plural': 'cancellation_reasons',
                'ordering': ('-created_at',),
                'default_related_name': 'cancellation_reasons',
                'indexes': [models.Index(fields=['id'], name='trips_cance_id_c1424d_idx')],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='cancellation_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trips.cancellationreason'),
        ),
    ]
