# Generated by Django 4.2.4 on 2023-08-16 13:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='status id')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='location')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.rideraccount', verbose_name='account')),
            ],
            options={
                'verbose_name': 'saved_location',
                'verbose_name_plural': 'saved_locations',
                'ordering': ('-created_at',),
                'default_related_name': 'saved_locations',
                'indexes': [models.Index(fields=['id', 'account'], name='locations_s_id_fcb294_idx')],
            },
        ),
    ]
